version: '{build}'
image: Visual Studio 2017
build_script:
- ps: |
    $ver = python version-prefix.py
    cd BlackMaple.SeedTactics.Scheduling
    If ($Env:APPVEYOR_REPO_TAG -eq "true") {
        dotnet pack -c Release /p:VersionPrefix=$ver --include-symbols
    } else {
        $suffix = "pre" + ($Env:APPVEYOR_BUILD_NUMBER).PadLeft(4, '0')
        dotnet pack -c Release /p:VersionPrefix=$ver --version-suffix $suffix --include-symbols
    }
artifacts:
- path: '**/*.nupkg'
